server.port=7056
spring.datasource.enable=true
spring.session.store-type=none
spring.profiles.active=dev
server.undertow.threads.worker=500

spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
spring.banner.location=classpath:banner.txt

#file watcher Related Config
file.nrt.sourcepath=C:/AML/AML-FILE-FOLDER/FILE-PROCESSOR-WATCH/amlnrtfiles/raw
file.nrt.destinationpath=C:/AML/AML-FILE-FOLDER/FILE-PROCESSOR-WATCH/filewatchcsvfile
file.nrt.processedpath=C:/AML/AML-FILE-FOLDER/FILE-PROCESSOR-WATCH/amlnrtfiles/processed/
file.nrt.fromfileformat=.flt
file.nrt.tofileformat=.csv
file.nrt.ismove=true
file.nrt.isdelete=false
file.nrt.filecount=4
#File Fetch Interval Time Config
file.nrt.fetchinterval=6000
#File Coppied stauscheck config.
file.nrt.completioncheckinterval=1000
file.nrt.parqutefilepath=C:/AML/AML-FILE-FOLDER/FILE-PROCESSOR-WATCH/PARQUTE
file.nrt.xmlroottag=root

##AML CBS files prefix and table names.
file.nrt.txntablenameprefix=ACC,ASA,ACT,BRN,NCB,CHQ,CNT,CRM,CST,EOD,INS,JTH,LCK,MCD,MAB,NOM,NCT,PRD,TBM,TTY,TRN
file.nrt.batchcount=100
file.nrt.dbtype=postgres
file.nrt.startconfigpath=C:/AML/AML-FILE-FOLDER/FILE-PROCESSOR-WATCH/config/mapping.json

hadoop.home.dir=C:/winutils

jasypt.encryptor.password=master
spring.datasource.url=jdbc:postgresql://aisworld.space:9000/fiuaml
spring.datasource.username=fiuaml
#spring.datasource.password=FINaml@DO_GRES_25
spring.datasource.password=ENC(n3EsWSaiUHCU/zm6YVgry/Zfc+aaA3XBzq4kGguTNzM=)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=amlschema

# Correct timezone property for HikariCP
spring.datasource.hikari.data-source-properties.TimeZone=Asia/Kolkata

# Optional Hibernate settings
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.datasource.hikari.initializationFailTimeout=60000


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# --- HikariCP Pool Settings (DuckDB is embedded, single connection only) ---
spring.datasource.hikari.pool-name=OracleHikariPool
# adjust based on DB limits # increase if you have many threads
spring.datasource.hikari.maximum-pool-size=10 
# keep a few idle connections
spring.datasource.hikari.minimum-idle=5
# 30s before idle connection is removed # 10 min
spring.datasource.hikari.idle-timeout=60000
# 30s max wait for a connection
spring.datasource.hikari.connection-timeout=30000
# 30min max lifetime of a connection # 30 min, less than DB timeout
spring.datasource.hikari.max-lifetime=1800000


# 5s timeout for validation
spring.datasource.hikari.validation-timeout=60000
spring.datasource.hikari.connection-test-query=SELECT 1

###Kafka Related Configurations Starting
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages="*"

#spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual
management.metrics.export.kafka.enabled=false

# Kafka Admin properties for topic configuration 
spring.kafka.admin.properties.retention.ms=60000
spring.kafka.admin.properties.cleanup.policy=delete


###Redis Config -amlhub.aisworld.space / 165.22.215.12210.122.0.3
spring.data.redis.host=aisworld.space
spring.data.redis.port=9200
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.ssl.enabled=true
#spring.data.redis.database=0
#spring.data.redis.username=user
#spring.data.redis.password=secret

#Logging purpose
logging.level.root=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.http=WARN
logging.level.org.duckdb=WARN

http.disable.method=HEAD,OPTIONS,TRACE,TRACK,DELETE
spring.thymeleaf.check-template-location=false
spring.jpa.open-in-view=false
spring.devtools.livereload.enabled=false